apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat1
  template:
    metadata:
      labels:
        app: tomcat1
    spec:
      containers:
        - name: tomcat
          image: tomcat
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
