---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 5; echo 'message from busybox2'"
