apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app1
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - repoURL: https://github.com/chengfang/multi-source-cmp.git
      targetRevision: HEAD
      path: apps/source1
      plugin:
        name: cmp-plugin-config
        env:
          - name: FOO
            value: "yes"
    - repoURL: https://github.com/chengfang/multi-source-cmp.git
      targetRevision: HEAD
      path: apps/source2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
