apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-app-with-discover
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - repoURL: https://github.com/chengfang/multi-source-cmp.git
      targetRevision: HEAD
      path: apps/source1
    - repoURL: https://github.com/chengfang/multi-source-cmp.git
      targetRevision: HEAD
      path: apps/source2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
